services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    volumes:
      - /episodes:/usr/src/app/episodes
      - /artwork:/usr/src/app/artwork
    ports:
      - 3000:3000