services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    volumes:
      - /Users/chrisk/code/tools/rss-feed-generator/episodes:/usr/src/app/episodes
      - /Users/chrisk/code/tools/rss-feed-generator/artwork:/usr/src/app/artwork
    ports:
      - 3000:3000