spring.application.name=rssgen

rss.artwork-dir=artwork
rss.episodes-dir=episodes
rss.info-dir=info
rss.rss-file-name=rss.xml
rss.show-file-name=show.json
rss.episode-file-extension=.mp3
rss.artwork-file-extension=.jpeg
rss.extract-artwork=false
rss.file-watch=true
rss.run-on-startup=false
rss.language=en-us
rss.error-log-file=parse-errors.log
rss.failure-limit=5
